# Generated by Django 5.2.5 on 2025-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nomecompleto',
            new_name='nome_completo',
        ),
    ]
