# Generated by Django 5.2.5 on 2025-08-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nomecompleto_usuarios_nome_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.modalidades'),
        ),
    ]
